1. What is a Python library? Why ^o we use Python libraries?1. What is a Python library? Why ^o we use Python libraries?

A library is a collection of code that makes everyday tasks more efficient. Using Seaborn, for example, you can generate visualisations with just one line of code. To create a chart from an object, you’d have to write a lot of code without a library like this. Python is a popular choice for data analysis because of its extensive library of tools for manipulating, visualising, and training machine learning models

2. What is the ^ifference between Numpy array an^ List?

NumPy is the fundamental package for scientific computing in Python. Numpy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences. Numpy is not another programming language but a Python extension module. It provides fast and efficient operations on arrays of homogeneous data. 



Some important points about Numpy arrays:

We can create an N-dimensional array in Python using Numpy.array().
The array is by default Homogeneous, which means data inside an array must be of the same Datatype. (Note You can also create a structured array in Python).
Element-wise operation is possible.
Numpy array has various functions, methods, and variables, to ease our task of matrix computation.
Elements of an array are stored contiguously in memory. For example, all rows of a two-dimensioned array must have the same number of columns. A three-dimensional array must have the same number of rows and columns on each card.





In [3]:
import numpy as np
a=np.array([1,2,3])#one dimensional array
print(a)

[1 2 3]


In [4]:
import numpy as np
b=np.array([[1,2,3,4]]) # two dimensional array 
print(b)

[[1 2 3 4]]


In [9]:
import numpy as np #three dimensional numpy array
c=np.array([[[1,2,3,4]]])
print(c)


[[[1 2 3 4]]]


What is Python List?
A Python list is a collection that is ordered and changeable. In Python, lists are written with square brackets. 

Some important points about Python Lists:

The list can be homogeneous or heterogeneous.
Element-wise operation is not possible on the list.
Python list is by default 1-dimensional. But we can create an N-Dimensional list. But then too it will be 1 D list storing another 1D list
Elements of a list need not be contiguous in memory

3. Fin^ the shape, size an^ ^imension of the following array?

In [2]:
import numpy as np

In [4]:
a=np.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])

In [5]:
#find the shape 
a.shape

(3, 4)

In [6]:
#find the size
a.size

12

In [7]:
# find the dimension
a.ndim

2

4. Write python co^e to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]

In [8]:
arr1=np.array(
[[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])
#accessing the first row of the element
first_row=arr1[0]
#print
print("first row",first_row)

first row [1 2 3 4]


5. How ^o you access the element at the thir^ row an^ fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [9]:
arr2=np.array(

[[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])
third_row_fourth_columns=arr2[2,3]

In [27]:
third_row_fourth_columns

12

6. Write co^e to extract all o^^-in^exe^ elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [15]:
arr3=np.array(

[[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])
odd_index_columns=arr3[:,1::2]
print("odd_index_columns",odd_index_columns)

odd_index_columns [[ 2  4]
 [ 6  8]
 [10 12]]


7.How can you generate a ran^om 3x3 matrix with values between 0 an^ 1?

In [23]:
np.random.rand(3,3)

array([[0.69738579, 0.47427013, 0.0424577 ],
       [0.79016885, 0.24763389, 0.79582887],
       [0.31706378, 0.64873401, 0.51697039]])

8. Describe the difference between np.ran^om.ran^ an^ np.ran^om.ran^n?

The difference between np.random.rand and np.random.randn lies in the distribution of the generated random numbers:

np.random.rand:
This function generates random numbers from a uniform distribution over the interval [0, 1).
When you use np.random.rand, you get random numbers that are uniformly distributed between 0 and 1.
The syntax for generating random numbers using np.random.rand is np.random.rand(d0, d1, ..., dn), where d0, d1, ..., dn are the dimensions of the array you want to create.

9. Write co^e to increase the ^imension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [25]:
arr1=np.array(

[[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])
increase_dim=np.expand_dims(arr1,axis=0)
print(increase_dim)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [27]:
increase_dim.ndim

3

10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [28]:
arr2=np.array(

[[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])

transpose_array=arr2.T
print("transpose array",transpose_array)

transpose array [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


11. Consi^er the following matrix:

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

In [31]:


a1=np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

b1=np.array([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])

# index wise multiplication 
a1*b1

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [39]:
#matrix multiplication

Matrix1=np.array( [[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])

Matrix2= np.array([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])
result=np.dot(Matrix1,Matrix2.T)
print("matrix multiplication")
print(result)

matrix multiplication
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]


In [40]:
Matrix1+Matrix2 #ADDING TWO MATRICES


array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [41]:
Matrix2-Matrix1 #substract the matrices

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [42]:
Matrix2/Matrix1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

12.  Which function in Numpy can be use^ to swap the byte or^er of an array?

In [46]:
array = np.array([1, 2, 3, 4], dtype=np.int32)
array.byteswap(True)
array

array([16777216, 33554432, 50331648, 67108864])

13.  What is the significance of the np.linalg.inv function?

13.The np.linalg.inv function in NumPy is used to compute the inverse of a square matrix. The significance of this function lies in its applications in various mathematical and scientific contexts, particularly in solving systems of linear equations and in performing transformations in linear algebra.

In [52]:
array=np.array([[2,4,],
                [6,8]])
np.linalg.inv(array)

array([[-1.  ,  0.5 ],
       [ 0.75, -0.25]])

14. What ^oes the np.reshape function ^o, an^ how is it use^?


The np.reshape function in NumPy is used to change the shape of an array without changing its data. It allows you to rearrange the elements of the array into a new shape while maintaining the same data.

In [60]:
import numpy as np
array1=np.array([1,2,3,4,5,6,])
np.reshape(array1,(2,3))

array([[1, 2, 3],
       [4, 5, 6]])

15. What is broa^casting in Numpy?

Broadcasting in NumPy is a powerful mechanism that allows arrays of different shapes to be combined in arithmetic operations, without explicitly reshaping them to have the same shape. It enables efficient element-wise operations between arrays of different shapes by automatically aligning their shapes and dimensions according to certain rules.


When operating on arrays of different shapes, NumPy compares their shapes element-wise. It starts with the trailing dimensions and works its way backward. Two dimensions are compatible for broadcasting if they are equal or one of them is 1. The arrays are then broadcasted along these dimensions to make their shapes compatible for the operation


Here are the key concepts of broadcasting in NumPy:

Scalar and Array Operations:=== Broadcasting allows you to perform operations between arrays and scalars, where the scalar is broadcasted to match the shape of the array.
Array-Array Operations:=== Broadcasting enables element-wise operations between arrays of different shapes. It extends the smaller array along the missing dimensions to match the shape of the larger array.
Implicit Copying:==== Broadcasting avoids making explicit copies of the data, which improves efficiency and reduces memory consumption.

In [62]:
import numpy as np

# Create a 3x3 array
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# Create a 1D array
arr2 = np.array([10, 20, 30])

# Add the 1D array to each row of the 2D array
arr1 + arr2



array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])